# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Machine Learning Project
email: 
description: > # this means to ignore newlines until "baseurl:"
    A project that applys machine learning algorithms on 
    data collected from imdb and twitter.  Can we train our data sets to 
    accurately predict the success of a film will gross from a matrix of 
    non-monetary features?  Does social media have an impact on on this 
    as well?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: blah
github_username: MachineLearningCSULA
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
